# !/usr/local/python
# -*- coding: UTF-8 -*-


class NonSelfOwnedManagePage(object):
    def __init__(self):
        self.nonselfiframe = '//iframe[@src="/xtboss/union400/resource/page/numberManage/numManage.jsp"]'
        self.btn_addnum = '//a[@id="add"]'
        self.btn_turn_to_own_number = '//a[@id="reservSelf"]'
        self.btn_transfer_to_agent = '//span[text()="转给代理商"]'
        self.btn_transfer_from_agent = '//span[text()="从代理商转出"]'
        self.search_business_number = '//input[@name="sns.number400"]'
        self.search_Preoccupation = '//input[@name="sns.capturename"]'
        self.search_reservations = '//input[@name="sns.subscribename"]'
        self.search_package_price_start = '//input[@id="start"]'
        self.search_package_price_end = '//input[@id="end"]'
        self.search_operator = '//input[@name="sns.category"]/preceding-sibling::input'
        self.search_two_level_classification = '//input[@name="sns.category2"]/preceding-sibling::input'
        self.search_state = '//input[@name="sns.status"]/preceding-sibling::input'
        self.search_account_number = '//input[@name="sns.accountname"]/preceding-sibling::input'
        self.search_number_category = '//input[@id="resever6"]/following-sibling::span/input'
        self.search_search_btn = '//span[text()="查询"]'
        self.frame_business_number = '//input[@id="sys_num"]'
        self.frame_predete_value = '//input[@id="ydj"]'
        self.frame_preoccupied_person = '//input[@id="yzr"]'
        self.frame_employee_selection = '//input[@id="ss"]'
        self.frame_employee_selection_search = '//input[@onclick="seachStaff()"]'
        self.frame_employee_selection_frambutton = '//span[text()="确定"]'
        self.frame_employee_selection_close = '//div[text()="员工选择"]/following-sibling::div'
        self.frame_ackage_value = '//input[@id="tcbj"]'
        self.frame_agentexclusive = '//input[@name="sne.sysNumadmin.resever4"]/preceding-sibling::input'
        self.frame_submit = '//span[@id="sub1"]'
        self.frame_addsuccessfram = '//div[text()="保存成功"]'
        self.frame_addsuccessfram_btn = '//div[text()="保存成功"]/following-sibling::div//span[text()="确定"]'
        self.tab_wait_text = '//div[text()="数据装载中......"]'
        self.btn_modify = '//div[@id="saff_mmData"]//div[@onclick="update()"]'
        self.frame_msg1 = '//div[contains(@class, "messager-body")]/div[1]'
        self.frame_tips1 = '//div[contains(@class, "tooltip tooltip-right")]/div[1]'
        self.release_btn = '//div[@id="saff_mmData"]//div[@onclick="realse()"]'
        self.msg_release = '//div[contains(text(),"将从公司内部库释放，是否释放")]'
        self.msg_release_btn = '//div[contains(text(),"将从公司内部库释放，是否释放")]/following-sibling::div//span[text()="确定"]'
        self.msg_release2 = '//div[text()="预占成功>>>释放"]'
        self.msg_release2_btn = '//div[text()="预占成功>>>释放"]/following-sibling::div//span[text()="确定"]'
        self.msg_release3 = '//div[text()="号码已经释放过"]'
        self.msg_release3_btn = '//div[text()="号码已经释放过"]/following-sibling::div//span[text()="确定"]'
        self.promotion_btn = '//div[@id="saff_mmData"]//div[@onclick="promotion()"]'
        self.msg_promotion = '//div[contains(text(),"将被设置为是促销号，是否设置")]'
        self.msg_promotion_btn = '//div[contains(text(),"将被设置为是促销号，是否设置")]/following-sibling::div//span[text()="确定"]'
        self.msg_promotion2 = '//div[text()="设置成功！"]'
        self.msg_promotion2_btn = '//div[text()="设置成功！"]/following-sibling::div//span[text()="确定"]'
        self.msg_promotion3 = '//div[contains(text(),"将被设置为非促销号，是否设置")]'
        self.msg_promotion3_btn = '//div[contains(text(),"将被设置为非促销号，是否设置")]/following-sibling::div//span[text()="确定"]'
